global:
  resolve_timeout: 5m

route:
  group_by: ["alertname"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: telegram
  routes:
    - receiver: telegram
      continue: true
    - match:
      receiver: admin

receivers:
  - name: "admin"
    email_configs:
      - to: "ntsibahdonald@gmail.com"
        from: "ridelntsoumou@gmail.com"
        smarthost: smtp.gmail.com:587
        auth_username: "ridelntsoumou@gmail.com"
        auth_identity: "ridelntsoumou@gmail.com"
        auth_password: "mnwt pzqb ukkg jciw"

  - name: "telegram"
    telegram_configs:
      - bot_token: 7482217455:AAEfH1OwFnlHV5EzL5oyAHtJOdfic99GgPc
        api_url: https://api.telegram.org
        chat_id: -4200889188
        parse_mode: ""
