global:
  scrape_interval: 15s # Fréquence de collecte des données
  evaluation_interval: 15s # Fréquence d'évaluation des règles

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "blackbox"
    metrics_path: /probe
    params:
      module: [http_2xx] # Choisissez le module blackbox à utiliser (ici pour vérifier les réponses HTTP 2xx)
    static_configs:
      - targets:
          - https://8b785262244d54ee92.gradio # Remplacez par l'URL que vous souhaitez sonder
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115 # Adresse du Blackbox Exporter

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"

rule_files:
  # Mentionner les fichiers de règles ici
  - "/etc/prometheus/myrules.yml"
